### ISSUE TITLE
Broken Link for Invoice Training Dataset

### ISSUE THREAD

**Issue by ppolyzos** [microsoft/ignite-learning-paths-training-aiml#37]
Great work on the documentation and really cool demos!

I noticed that the link found in [demo2 page](https://github.com/microsoft/ignite-learning-paths-training-aiml/blob/master/aiml10/demo2.md) for the [Invoice Training Set](https://globaleventcdn.blob.core.windows.net/assets/aiml/aiml10/data/train.zip) is broken.

It would be really helpful if you could update the link with a valid one.

**Comment by amynic** [comment]
Hi @ppolyzos - let me take a look and fix that, thanks for this feedback ⭐

**Comment by amynic** [comment]
Updated the link to the training dataset .. I will also review all links to datasets to reconfirm asap

**Comment by amynic** [comment]
all links in AIML10 documentation have been checked and should now be working - thank you for raising this to us :)
