### ISSUE TITLE
AIML20 vision_demo.sh link updates needed

### ISSUE THREAD

**Issue by amynic** [microsoft/ignite-learning-paths-training-aiml#55]
In AIML20 vision_demo.sh file has links to old repo ignite-learning-paths rather than ignite-learning-paths-training-aiml since merge of repos. images linked are drill and man wearing hardhat

**Comment by amynic** [comment]
working on and testing fix now ...

**Comment by amynic** [comment]
Commited and tested using Azure Cloud Shell: https://github.com/microsoft/ignite-learning-paths-training-aiml/commit/dedd5d6fc187aaa446dbadd05df842399b8ef390 @revodavid could I double check your happy with this change?

**Comment by revodavid** [comment]
Those changes look correct to me

**Comment by amynic** [comment]
Brilliant - closing the issue as solved with this commit: https://github.com/microsoft/ignite-learning-paths-training-aiml/commit/dedd5d6fc187aaa446dbadd05df842399b8ef390
