### ISSUE TITLE
The AIML40 data uploaded by the script is corrupt

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/ignite-learning-paths-training-aiml#60]
After uploading the dataset for demo2 using the workaround detailed in #59, the data that is uploaded appears to be corrupt:

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/1710385/72018414-731d6200-321c-11ea-85e4-62aff1924bdc.png">

**Comment by shwars** [comment]
Thank you for bringing this issue up, the manual procedure for uploading Excel file will take care of the correct format. I will close the issue once the updated readme is on the portal..

**Comment by amynic** [comment]
I have merged the pull request with the updates and corrections - thank you @shwars for your hard work here and making the content better for everyone
