### ISSUE TITLE
Please clarify the path to the csv file in AIML30

### ISSUE THREAD

**Issue by rohancragg** [microsoft/ignite-learning-paths-training-aiml#67]
I'm not sure what the 'correct path' will be for the uploaded csv file in the .ipynb.

In Datasets I see a relative path property for the file after uploading but I tried that and I get a FileNotFoundError.

**Comment by amynic** [comment]
this code was designed to simply upload the forecasting dataset to the Jupyter Notebook VM local drive and access it simply through aiml30/python/ForecastingData.csv for example. I have now added more clarity here: https://github.com/microsoft/ignite-learning-paths-training-aiml/commit/41bfae7520394b778977dbf13d65b64c29f2d8f7

We will also work on adding sample code to retrieve from the datastore in AML as another example

**Comment by amynic** [comment]
added code to connect to your datasource (ForecastingData) from the AML studio - this is under the Load Data heading as a commented out cell: https://github.com/microsoft/ignite-learning-paths-training-aiml/commit/6d485879a56aa3bd08a3e7605b39c68de1e27ce1

**Comment by rohancragg** [comment]
Thanks, I also found that this path works (given that you've already cloned the repo):
csv_file = "/mnt/azmnt/code/Users/ignite-learning-paths-training-aiml/aiml30/C#/IgniteAimlDataApp/IgniteAimlDataApp/Datasets/ForecastingData.csv"

**Comment by amynic** [comment]
Great testing! Thanks for sharing - also you may be able to complete a relative path - so ...
csv_file = "../C#/IgniteAimlDataApp/IgniteAimlDataApp/Datasets/ForecastingData.csv" to come out of the Python folder and into the C# folder in the repo
