### ISSUE TITLE
Please clarify Compute types required in demo

### ISSUE THREAD

**Issue by rohancragg** [microsoft/ignite-learning-paths-training-aiml#68]
In `blob/master/aiml30/README-Attendee.md` please clarify the Compute type that should be created. The UI now separates Notebook VM / Training / Inference. I assume that the Kubernetes compute should be created under Inference for example...

**Comment by amynic** [comment]
Hi @rohancragg thank you for this feedback - very good spot - let me fix this and report back asap

**Comment by amynic** [comment]
Hi @rohancragg sorry for the delay - I have updated the instructions with further updated details - see commit here: https://github.com/microsoft/ignite-learning-paths-training-aiml/commit/ebcb3d491c64f1815f0fcde449cd6f61ff61911c
