### ISSUE TITLE
AIML40: No compute available to profile dataset

### ISSUE THREAD

**Issue by revodavid** [microsoft/ignite-learning-paths-training-aiml#74]
In README.md where it says:

> Click Next two times,0 on the final page select Profile the dataset after creating and click Create.

It is not possible to check "Profile the dataset" until a Notebook VM has been created, which has not yet happened at this point in the setup process.

**Comment by amynic** [comment]
Very good spot @revodavid lets see how we can get this fixed for others

**Comment by amynic** [comment]
OK after reviewing it looks like we talk about profiling the dataset further down the page after creating the training compute - so I will remove it from the line you mention above and the profiling will happen later in the process. Thanks for this feedback

**Comment by amynic** [comment]
changes made to readme: https://github.com/microsoft/ignite-learning-paths-training-aiml/commit/cefd68a0d2b3777139ee1032b82d6b33518ca5f1 please let me know if you think this fixes the problem and I will close the issue
