### ISSUE TITLE
got unknown error on aiml50 demonstration setup 

### ISSUE THREAD

**Issue by easonlai** [microsoft/ignite-learning-paths-training-aiml#75]
Hi

Need some help, I got below unknown error when try to deploy aiml50 demonstration. And I'm already follow through setup instruction... Please help...

    "properties": {
        "statusCode": "BadRequest",
        "serviceRequestId": null,
        "statusMessage": "{\"error\":{\"code\":\"InvalidTemplateDeployment\",\"message\":\"The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '2a482f22-cca8-4664-bb71-cc9e4ea74360'. See inner errors for details.\",\"details\":[{\"code\":\"ValidationForResourceFailed\",\"message\":\"Validation failed for a resource. Check 'Error.Details[0]' for more information.\",\"details\":[{\"code\":\"ServerFarmNotFound\",\"message\":\"The specified app service plan was not found.\"}]}]}}"
    },

Thanks

**Comment by easonlai** [comment]
Tested in regions, southeastasia; eastus; eastus2; westus2, all failed and got same error ...

**Comment by amynic** [comment]
Hi @easonlai thank you for reporting this we will start investigating @FBoucher  and @smurawski this is the same error in AIML20 for some regions specified app service plan not found - but this should be created with the app service I assume, anything you would look for in the ARM template first?

**Comment by usepowershell** [comment]
@amynic @easonlai I think the full name of the app service sku changed.  I've got a pull request to update the AIML50 deployment to remove that and just use the short sku name. https://github.com/microsoft/ignite-learning-paths-training-aiml/pull/76

**Comment by amynic** [comment]
testing new template now before merging

**Comment by usepowershell** [comment]
@amynic That started to work at first, but now I'm getting invalid again. :/

**Comment by amynic** [comment]
template now fixed and tested - just merged this into the master branch of the repo. @easonlai thank you for reporting, please update your forked repo and check this fix works. https://github.com/microsoft/ignite-learning-paths-training-aiml/pull/76

**Comment by easonlai** [comment]
Awesome, just test and successfully deployed. Thanks for your promptly help :)

**Comment by amynic** [comment]
Amazing work @smurawski on the quick turnaround 👍✅🏆
