### ISSUE TITLE
AIML10 - Relative Import error when running Reader Skill locally

### ISSUE THREAD

**Issue by Lee-Myhre** [microsoft/ignite-learning-paths-training-aiml#77]
Received this error while testing Demo 3 of the AIML demos, during local run:

```
A ScriptHost error has occurred
Exception while executing function: Functions.AnalyzeInvoice. Microsoft.Azure.WebJobs.Script: Traceback (most recent call last):
  File "D:\Internal\Trainings\ignite-learning-paths-training-aiml-master\aiml10\src\InvoiceReaderSkill\AnalyzeInvoice\func.py", line 7, in <module>
    from . import helpers
ImportError: attempted relative import with no known parent package
.

```

As far as I can tell I followed the instructions perfectly, which from my experience usually means I need to "down-date" one of the tools back to the version from when the demo was published. Any ideas?

**Comment by amynic** [comment]
@sethjuarez have you seen this Functions error before at all with relation to the AIML10 demos?

**Comment by amynic** [comment]
@Lee-Myhre could you confirm this is the section you are finding this error? https://github.com/microsoft/ignite-learning-paths-training-aiml/blob/master/aiml10/demo3.md#run-the-azure-function-locally running the code locally?

**Comment by amynic** [comment]
@Lee-Myhre can I also double check your function code setup looks like this - where 'from . import helpers' is trying to access the helpers.py file in the same directory folder 
![image](https://user-images.githubusercontent.com/13828867/74673694-a225dc80-51a7-11ea-8827-677239c9fae2.png)

**Comment by Lee-Myhre** [comment]
Nope, it looks like the .python_packages folder wasn't created. I worked with Python academically a few years ago but this is my first time with it since and definitely my first with this computer; I must have missed downloading the required libraries.

Do you by chance know the command I need to run?

**Comment by Lee-Myhre** [comment]
Surprisingly, though, the helpers.py file *is* there.
![image](https://user-images.githubusercontent.com/22507239/74675341-36704f00-5168-11ea-8f60-cefc08621870.png)

When I tried swapping out the import for "from helpers import *" it could see the file, but I got yet another error about dateutil:
`
[2020-02-17 5:33:55 PM] A ScriptHost error has occurred
[2020-02-17 5:33:55 PM] Exception while executing function: Functions.AnalyzeInvoice. Microsoft.Azure.WebJobs.Script: Traceback (most recent call last):
[2020-02-17 5:33:55 PM]   File "D:\Internal\Trainings\ignite-learning-paths-training-aiml-master\aiml10\src\InvoiceReaderSkill\AnalyzeInvoice\func.py", line 7, in <module>
[2020-02-17 5:33:55 PM]     from helpers import *
[2020-02-17 5:33:55 PM]   File "D:\Internal\Trainings\ignite-learning-paths-training-aiml-master\aiml10\src\InvoiceReaderSkill\AnalyzeInvoice\helpers.py", line 2, in <module>
[2020-02-17 5:33:55 PM]     from dateutil import parser
[2020-02-17 5:33:55 PM] ModuleNotFoundError: No module named 'dateutil'
[2020-02-17 5:33:55 PM] .
`

**Comment by amynic** [comment]
> Nope, it looks like the .python_packages folder wasn't created. I worked with Python academically a few years ago but this is my first time with it since and definitely my first with this computer; I must have missed downloading the required libraries.
> 
> Do you by chance know the command I need to run?

Maybe it would be worth running through the basic python installation, selecting the environment in VS code and then installing (via pip in the terminal in VS code) the packages from the requirements.txt folder. Then we can work from there as to what might be missing for you to run this code locally? https://code.visualstudio.com/docs/languages/python

**Comment by amynic** [comment]
@Lee-Myhre did the above help at all - keen to understand what extra install information we can add so others in the same position can get around this obstacle?

**Comment by Lee-Myhre** [comment]
To get the missing files, I did have to use the requirements file. the above link actually doesn't mention the Requirements file at all, so I had to go through the help for the PIP tool to build myself a command:
pip install -r requirements.txt -t .python_packages --upgrade
(the --upgrade is just so it automatically handles replacing if I ever end up having to run it again.)

I'm now getting an empty response, but it's a step up from an error response for sure.

**Comment by amynic** [comment]
Hi ok this is great feedback let me see if a can incorporate more instructions on installation and pip for users

Please could you provide more detail on the empty response is this once the local URI is running and you send the request to the local URI from postman? Or somewhere else?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Lee-Myhre** [comment]
I should be clear, I still was unable to make it work with the original import statement, even after installing the packages. the two options I found that worked best each had caveats:
1. `from helpers import *`
this worked but there were a bunch of additional warnings created because additional functions were now being loaded but unused.
2. `from helpers import convert`
from what I saw this is the only function from the helpers file that is actually being used, so we can do it this way to avoid having to import the other functions; however wording the import this way required that I remove the "helpers" prefix when the function is called on line 59.

Regarding the new error, yes, I am still on the same step, running locally. I get headers, with content length of 0. I originally assumed this was about the SAS expiring since it defaults to only last a single day but even after renewing this I get the same thing - a HTTP 200 OK response, Content-Length 0, no Body at all. Going back through the documentation to see if I missed anything there, and then on to the documentation for Skills in case there's something missing on that front.

**Comment by sethjuarez** [comment]
If you want to just get it running you can pull the entire convert function into the main func.py - that should fix it!

**Comment by amynic** [comment]
@Lee-Myhre did Seth's suggestion fix this issue?

**Comment by amynic** [comment]
@Lee-Myhre did Seth's suggestion fix this issue?

**Comment by amynic** [comment]
Closing issue
