### ISSUE TITLE
Extra column in sample csv

### ISSUE THREAD

**Issue by jason-theodorakopoulos** [microsoft/ignite-learning-paths-training-aiml#78]
There is an extra column at the end of https://github.com/microsoft/ignite-learning-paths-training-aiml/blob/master/aiml30/C%23/IgniteAimlDataApp/IgniteAimlDataApp/Datasets/ForecastingData.csv that causes some troubles

**Comment by amynic** [comment]
Hi @jason-theodorakopoulos  - thanks for letting us know. @cassieview do you have some bandwidth to look at the Forecasting file and check why it might be causing errors. 
@jason-theodorakopoulos coudl you explain further when, where and what the issues was with the ForecastingData.csv file?

**Comment by jason-theodorakopoulos** [comment]
![image](https://user-images.githubusercontent.com/57361398/74735396-49168100-5259-11ea-8534-56604160b256.png)
The last column highlighted in yellow - I am not sure it is supposed to be there or it was added by mistake. 
I removed it from the dataset - to make the demo c# code work.

**Comment by cassiebreviu** [comment]
There is an extra column to be deleted in the dataset that is in the repo. If you download and replace the existing dataset with the new dataset, the extra column is removed. I will update the repo so the default dataset has the column removed as well. Thanks!

**Comment by amynic** [comment]
Brilliant thanks for the quick investigation @cassieview - will keep an eye out for the pull request and then close this issue pointing to it :)

**Comment by amynic** [comment]
@cassieview updated the default spreadsheet to the new format so it will not throw an error. However the instructions state a new spreadsheet should be downloaded to replace this so the dates you are presenting at current and not old.

the update relates to pull request: https://github.com/microsoft/ignite-learning-paths-training-aiml/pull/79

Now closing this issue
