### ISSUE TITLE
AIML40 bug 2

### ISSUE THREAD

**Issue by lokinfey** [microsoft/ignite-learning-paths-training-aiml#90]
I found another problem in AIML 40 demo2, when I use clothing_automl.xlsx it to dataset , I found preview show error like this ，characters are garbled。  I use UTF-8 ..........

![123](https://user-images.githubusercontent.com/4607663/79204825-bcaac800-7e6f-11ea-8b0d-7d47b2ea8b7c.PNG)

**Comment by cassiebreviu** [comment]
@lokinfey Change format to Tabular

**Comment by amynic** [comment]
@lokinfey please confirm when changing this to tabular the setup works? I will then close this issue

**Comment by amynic** [comment]
The instructions confirm the need for the dataset to be uploaded in Tabular format - therefore I am closing this issue. Thank you for sharing
